In [2]:
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout

Using TensorFlow backend.


In [3]:
def createModel():
    model = Sequential()
    model.add(Dense(5, input_shape=(1,5), name="Input"))
    model.add(Activation('relu'))
    model.add(Dropout(.2))
    model.add(Dense(10, name="Hidden1"))
    model.add(Activation('relu'))
    model.add(Dropout(.2))
    model.add(Dense(10, name="Hidden2"))
    model.add(Activation('relu'))
    model.add(Dropout(.2))
    model.add(Dense(2, name="Output"))
    model.add(Activation('softmax'))
    return model

In [4]:
model = createModel()

In [5]:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [6]:
import numpy as np

In [7]:
from random import randint
x1 = randint(1, 10)
x2 = randint(1, 10)
x3 = randint(1, 10)
x4 = randint(1, 10)
x5 = randint(1, 10)

args = [x1,x2,x3,x4,x5]
args_rev = args[::-1]

args_comb = [args] + [args_rev]

arr = np.array(args_comb)

In [8]:
arr = arr.reshape(2,1,5)

In [9]:
arr.shape

(2, 1, 5)

In [10]:
arr

array([[[3, 9, 2, 2, 3]],

       [[3, 2, 2, 9, 3]]])

In [11]:
pred = model.predict(arr)

In [12]:
pred

array([[[0.00255029, 0.9974497 ]],

       [[0.01600836, 0.98399156]]], dtype=float32)

# Replacing weights

In [24]:
layer = model.layers[3]

In [25]:
weights = layer.get_weights()

In [26]:
weights

[array([[0.68709666, 0.00389893, 0.4778332 , 0.09735183, 0.7456636 ,
         0.35686228, 0.603749  , 0.4844827 , 0.58336043, 0.30859175],
        [0.81550896, 0.1905326 , 0.564541  , 0.9538613 , 0.4705858 ,
         0.85007066, 0.442197  , 0.4587548 , 0.11953949, 0.3656184 ],
        [0.75793403, 0.22877388, 0.6748403 , 0.5532583 , 0.7236561 ,
         0.46590307, 0.43366745, 0.14266299, 0.9305271 , 0.34183744],
        [0.4640215 , 0.1576865 , 0.680114  , 0.643063  , 0.4065798 ,
         0.9177542 , 0.5715427 , 0.03138895, 0.8640229 , 0.9659217 ],
        [0.4660373 , 0.39576408, 0.15076616, 0.9051012 , 0.47864276,
         0.9609595 , 0.3117343 , 0.59475225, 0.621871  , 0.56589925]],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)]

In [27]:
ws = weights[0]
bs = weights[1]

In [28]:
ws

array([[0.68709666, 0.00389893, 0.4778332 , 0.09735183, 0.7456636 ,
        0.35686228, 0.603749  , 0.4844827 , 0.58336043, 0.30859175],
       [0.81550896, 0.1905326 , 0.564541  , 0.9538613 , 0.4705858 ,
        0.85007066, 0.442197  , 0.4587548 , 0.11953949, 0.3656184 ],
       [0.75793403, 0.22877388, 0.6748403 , 0.5532583 , 0.7236561 ,
        0.46590307, 0.43366745, 0.14266299, 0.9305271 , 0.34183744],
       [0.4640215 , 0.1576865 , 0.680114  , 0.643063  , 0.4065798 ,
        0.9177542 , 0.5715427 , 0.03138895, 0.8640229 , 0.9659217 ],
       [0.4660373 , 0.39576408, 0.15076616, 0.9051012 , 0.47864276,
        0.9609595 , 0.3117343 , 0.59475225, 0.621871  , 0.56589925]],
      dtype=float32)

In [29]:
new = np.random.random(ws.shape)

In [30]:
layer.set_weights([new, bs])

In [31]:
new

array([[0.34619355, 0.78815415, 0.66645933, 0.07074307, 0.35905978,
        0.43294984, 0.57106119, 0.57095519, 0.31023495, 0.23307156],
       [0.5185442 , 0.88355282, 0.06887752, 0.29282847, 0.35405776,
        0.43620524, 0.15331038, 0.96098771, 0.03960641, 0.97660408],
       [0.68005302, 0.22549359, 0.47190363, 0.34808027, 0.23792695,
        0.79826751, 0.37889407, 0.40632584, 0.12271105, 0.44278524],
       [0.19538664, 0.47884798, 0.42823959, 0.223527  , 0.01330779,
        0.24070815, 0.64917733, 0.73301297, 0.41252956, 0.00831456],
       [0.7731382 , 0.49327241, 0.91111361, 0.56920539, 0.0387816 ,
        0.44659093, 0.07821134, 0.21125174, 0.90404244, 0.82644779]])

In [32]:
model.layers[3].get_weights()

[array([[0.34619355, 0.7881541 , 0.6664593 , 0.07074307, 0.35905978,
         0.43294984, 0.5710612 , 0.5709552 , 0.31023496, 0.23307157],
        [0.5185442 , 0.88355285, 0.06887752, 0.29282847, 0.35405776,
         0.43620524, 0.15331037, 0.9609877 , 0.03960641, 0.9766041 ],
        [0.680053  , 0.22549358, 0.47190362, 0.34808028, 0.23792695,
         0.79826754, 0.37889406, 0.40632585, 0.12271105, 0.44278523],
        [0.19538663, 0.47884798, 0.42823958, 0.223527  , 0.01330779,
         0.24070816, 0.6491773 , 0.733013  , 0.41252956, 0.00831456],
        [0.7731382 , 0.4932724 , 0.9111136 , 0.5692054 , 0.03878159,
         0.44659093, 0.07821134, 0.21125175, 0.9040424 , 0.8264478 ]],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)]